### ISSUE TITLE
How to get shared text?

### ISSUE THREAD

**Issue by rafaeljustinox** [AboutShout/share_handler#4]
I can't find a method like `handler.sharedMediaStream` to get the text?
There's no example of receiving text/url.

**Comment by SethuSenthil** [comment]
Yup, I was wondering the same thing. There seems to be no other method for receiving shared text within the dart source code.

**Comment by JoshJuncker** [comment]
The SharedMedia object has a 'content' attribute. That is where a shared url or shared text is. So it is the same method and stream for either text or file/s.

**Comment by JoshJuncker** [comment]
@rafaeljustinox Does that answer your question? Am I good to close this?

**Comment by rafaeljustinox** [comment]
@JoshJuncker Yep! Thanks
